declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_APPWRITE_KEY: string;
    NEXT_PUBLIC_APPWRITE_ENDPOINT: string;
    NEXT_PUBLIC_APPWRITE_PROJECT: string;
    NEXT_PUBLIC_APPWRITE_PROJECT: string;
    NEXT_PUBLIC_APPWRITE_DATABASE: string;
    NEXT_PUBLIC_APPWRITE_COLLECTION_GRADES: string;
    NEXT_PUBLIC_APPWRITE_COLLECTION_TRANSACTIONS: string;
    NEXT_PUBLIC_APPWRITE_COLLECTION_ASSESSMENTS: string;
    NEXT_PUBLIC_APPWRITE_COLLECTION_SUBJECTS: string;
    NEXT_PUBLIC_APPWRITE_COLLECTION_STUDENTS: string;
    NEXT_PUBLIC_APPWRITE_COLLECTION_TEACHERS: string;
    NEXT_PUBLIC_APPWRITE_COLLECTION_MATERIALS: string;
    NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_FILES: string;
    NEXT_PUBLIC_URL: string;
  }
}
