import type { Metadata } from 'next';
import '../globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import AppSidebar from '@/projects/components/AppSidebar';
import AppNavbar from '@/projects/components/AppNavbar';
import localFont from 'next/font/local';
import { AutoBreadcrumb } from '@/projects/components/AutoBreadcrumb';
import AuthWrapper from '@/projects/providers/AuthWrapper';
import getStudent from '@/lib/actions/getStudent';
import { getLoggedInUser } from '@/lib/server/appwrite';
import getTeacher from '@/lib/actions/getTeacher';

// const geistMono = localFont({
//   src: [
//     {
//       path: '../../fonts/GeistMono[wght].ttf',
//       weight: '100 900', // Adjust based on your font's supported weights
//       style: 'normal',
//     },
//   ],
//   variable: '--font-geist-mono',
//   display: 'swap',
// });

// const geistSans = localFont({
//   src: [
//     {
//       path: '../../fonts/Geist[wght].ttf',
//       weight: '100 750 900',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-geist',
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: 'Testing Lang',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isAuth = false;
  const { user } = await getLoggedInUser();

  if (user) {
    const { documents: student } = await getStudent(user.id);
    if (student.length > 0) {
      isAuth = true;
    } else {
      const { documents: teacher } = await getTeacher(user.id);
      if (teacher.length > 0) {
        isAuth = true;
      }
    }
  }

  return (
    <div className={` antialiased flex`}>
      <SidebarProvider>
        {isAuth ? <AppSidebar></AppSidebar> : ''}
        <main className='w-full'>
          <AppNavbar></AppNavbar>
          <AutoBreadcrumb className='px-4 hidden md:block' />

          {children}
        </main>
      </SidebarProvider>
    </div>
  );
}
