import type { Metadata } from 'next';
import '../globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import AppSidebar from '@/projects/components/AppSidebar';
import AppNavbar from '@/projects/components/AppNavbar';
import localFont from 'next/font/local';
import { AutoBreadcrumb } from '@/projects/components/AutoBreadcrumb';
import AuthWrapper from '@/projects/providers/AuthWrapper';

// const geistMono = localFont({
//   src: [
//     {
//       path: '../../fonts/GeistMono[wght].ttf',
//       weight: '100 900', // Adjust based on your font's supported weights
//       style: 'normal',
//     },
//   ],
//   variable: '--font-geist-mono',
//   display: 'swap',
// });

// const geistSans = localFont({
//   src: [
//     {
//       path: '../../fonts/Geist[wght].ttf',
//       weight: '100 750 900',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-geist',
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: 'Testing Lang',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthWrapper>
      <div className={` antialiased flex`}>
        <SidebarProvider>
          <AppSidebar></AppSidebar>
          <main className='w-full'>
            <AppNavbar></AppNavbar>
            <AutoBreadcrumb className='px-4 hidden md:block' />

            {children}
          </main>
        </SidebarProvider>
      </div>
    </AuthWrapper>
  );
}
