import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';

import ThemeWrapper from '@/projects/providers/ThemeWrapper';

export const metadata: Metadata = {
  title: 'Create Next Apps',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        <ThemeWrapper>{children}</ThemeWrapper>
        <Toaster className='pointer-events-auto' />
      </body>
    </html>
  );
}
